# Generated by Django 5.2.1 on 2025-05-22 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='I am a dedicated Mechanical Engineering student at Texas State University with a passion for design, innovation, and problem-solving. With hands-on experience in CAD software, 3D printing technologies, and automotive maintenance, I am constantly seeking opportunities to apply engineering principles to real-world challenges.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, help_text='Optional link for more details')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('availability', models.CharField(default='Mon-Fri: 9am - 6pm CST', max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('graduation_date', models.CharField(max_length=100)),
                ('gpa', models.CharField(blank=True, max_length=20)),
                ('honors', models.TextField(blank=True, help_text='Comma-separated honors/achievements')),
                ('coursework', models.TextField(blank=True, help_text='Relevant coursework description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achievements', models.TextField(help_text='Bullet points separated by newlines')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='Brief description for the project card')),
                ('image', models.URLField(help_text='URL to project image')),
                ('category', models.CharField(choices=[('cad', 'CAD Design'), ('prototypes', 'Prototypes'), ('simulations', 'Simulations'), ('consulting', 'Consulting')], max_length=20)),
                ('date', models.CharField(help_text="e.g., 'December 2024'", max_length=50)),
                ('duration', models.CharField(help_text="e.g., '6 weeks'", max_length=50)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=200)),
                ('project_url', models.URLField(blank=True, help_text='Link to full project details')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Featured Project',
                'verbose_name_plural': 'Featured Projects',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default="HELLO, I'M", max_length=100)),
                ('name', models.CharField(default='MARCELO SALINAS', max_length=100)),
                ('title', models.CharField(default='Mechanical Engineering Student & Designer', max_length=200)),
                ('description', models.TextField(default='Specializing in innovative mechanical solutions and 3D modeling for complex engineering challenges. I transform concepts into functional products with precision and creativity.')),
                ('model_3d', models.FileField(blank=True, help_text='Upload a .glb or .gltf file for the 3D model', null=True, upload_to='hero_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])])),
                ('primary_button_text', models.CharField(default='VIEW MY WORK', max_length=50)),
                ('secondary_button_text', models.CharField(default='GET IN TOUCH', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(help_text='Upload a .glb or .gltf file', upload_to='3d_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])])),
                ('parts_count', models.CharField(help_text="e.g., '142 components'", max_length=50)),
                ('created_date', models.CharField(help_text="e.g., 'June 12, 2023'", max_length=50)),
                ('software_used', models.CharField(help_text="e.g., 'SolidWorks 2023'", max_length=100)),
                ('dimensions', models.CharField(help_text="e.g., '450mm × 320mm × 280mm'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '3D Model',
                'verbose_name_plural': '3D Models',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Marcelo Salinas - Portfolio', max_length=200)),
                ('footer_text', models.CharField(default='© 2024 Marcelo Salinas. All rights reserved.', max_length=200)),
                ('projects_section_title', models.CharField(default='FEATURED PROJECTS', max_length=100)),
                ('projects_section_description', models.TextField(default='Explore my latest mechanical engineering projects including 3D models, prototypes, and functional designs.')),
                ('models_section_title', models.CharField(default='3D MODEL EXPLORER', max_length=100)),
                ('models_section_description', models.TextField(default='Interact with some of my detailed 3D models. Rotate, zoom, and explore the engineering details.')),
                ('contact_section_title', models.CharField(default='CONTACT ME', max_length=100)),
                ('contact_section_description', models.TextField(default='Interested in working together? Feel free to reach out for collaborations or just a friendly hello.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(help_text="Use 'Present' for current jobs", max_length=50)),
                ('responsibilities', models.TextField(help_text='Bullet points separated by newlines')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(blank=True, help_text="e.g., 'Expert', 'Intermediate'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
