# Generated by Django 5.2.1 on 2025-05-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='RESUME', max_length=100)),
                ('description', models.TextField(default='Want my resume as a PDF?')),
                ('button_text', models.CharField(default='Download Resume', max_length=50)),
                ('resume_url', models.URLField(help_text='Direct link to resume PDF')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume Section',
                'verbose_name_plural': 'Resume Section',
            },
        ),
    ]
